// @poopdeck.gl/core
// SPDX-License-Identifier: MIT
// Copyright (c) @poopdeck.gl/core contributors

/**
 * Render a Markdown capability matrix from the backends' {@link BackendDescriptor}s
 * — the generated replacement for the hand-written parity table in
 * docs/roadmap/three-renderer-parity.md §3 (see
 * docs/roadmap/renderer-abstraction-2026-06.md §4.3 tier 5). The committed doc
 * (docs/spec/backend-capabilities.md) is produced by running
 * `node scripts/gen-capabilities-doc.mjs` and should be regenerated by hand
 * whenever a BackendDescriptor changes — there is currently no automated test
 * that regenerates and diffs it, so nothing catches the doc drifting out of
 * sync on its own.
 */

import { LAYER_KINDS, CAPABILITIES, type BackendDescriptor, type LayerKind } from './capabilities';
import type { TimeFilterMode } from './time-filter';

const ALL_MODES: TimeFilterMode[] = ['none', 'window', 'wake', 'cumulative', 'trail'];

function layerCell(support: BackendDescriptor['layerKinds'][LayerKind]): string {
  if (support.supported) return '✅';
  if ('fallbackKind' in support && support.fallbackKind) return `↳ ${support.fallbackKind}`;
  return '—';
}

/** Build the full Markdown document (deterministic; no timestamps). */
export function renderCapabilitiesMarkdown(descriptors: readonly BackendDescriptor[]): string {
  const ids = descriptors.map((d) => d.id);
  const head = (label: string) => `| ${label} | ${ids.join(' | ')} |`;
  const sep = `| --- | ${ids.map(() => '---').join(' | ')} |`;
  const lines: string[] = [];

  lines.push("<!-- GENERATED by @poopdeck.gl/core renderCapabilitiesMarkdown from each backend's");
  lines.push('     BackendDescriptor. Do not edit by hand — regenerate with');
  lines.push('     `node scripts/gen-capabilities-doc.mjs` (see that file\'s header for the');
  lines.push('     build-first invocation) whenever a BackendDescriptor changes. There is');
  lines.push('     currently no automated check that this file stays in sync with the');
  lines.push('     descriptors, so regeneration is a manual step. -->');
  lines.push('# STT backend capability matrix');
  lines.push('');

  lines.push('## Traits');
  lines.push(head('Trait'));
  lines.push(sep);
  lines.push(`| projectsOnCpu | ${descriptors.map((d) => (d.projectsOnCpu ? 'yes' : 'no')).join(' | ')} |`);
  lines.push(`| tilesetOwnership | ${descriptors.map((d) => d.tilesetOwnership).join(' | ')} |`);
  lines.push(`| pickMechanism | ${descriptors.map((d) => d.pickMechanism).join(' | ')} |`);
  lines.push(`| interleavedBasemap | ${descriptors.map((d) => (d.interleavedBasemap ? 'yes' : 'no')).join(' | ')} |`);
  lines.push(`| basemapProjection | ${descriptors.map((d) => d.basemapProjection).join(' | ')} |`);
  lines.push('');

  lines.push('## Capabilities');
  lines.push(head('Capability'));
  lines.push(sep);
  for (const cap of CAPABILITIES) {
    lines.push(`| ${cap} | ${descriptors.map((d) => (d.capabilities[cap] ? '✅' : '—')).join(' | ')} |`);
  }
  lines.push('');

  lines.push('## Time-filter modes');
  lines.push(head('Mode'));
  lines.push(sep);
  for (const mode of ALL_MODES) {
    lines.push(`| ${mode} | ${descriptors.map((d) => (d.timeFilterModes.includes(mode) ? '✅' : '—')).join(' | ')} |`);
  }
  lines.push('');

  lines.push('## Layer kinds (✅ native · ↳ fallback · — unsupported)');
  lines.push(head('Layer kind'));
  lines.push(sep);
  for (const kind of LAYER_KINDS) {
    lines.push(`| ${kind} | ${descriptors.map((d) => layerCell(d.layerKinds[kind])).join(' | ')} |`);
  }
  lines.push('');

  return lines.join('\n');
}
