/**
 * Cross-language contract test: read a real archive produced by the Rust
 * `stt-build` CLI (`test/fixtures/sample.stt`) through the TypeScript reader.
 *
 * This is the single most important test in the package — it proves the Rust
 * writer and the TS reader agree on the on-disk format.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { STTArchive } from '../src/archive';
import { encodeDirectory } from '../src/directory';
import { GeometryType } from '../src/types';

const FIXTURE = fileURLToPath(new URL('./fixtures/sample.stt', import.meta.url));
const FIXTURE_BYTES = readFileSync(FIXTURE);
const HEADER_SIZE = 64;

/**
 * A `fetch` shim that serves the fixture file with HTTP Range semantics —
 * exactly what `STTArchive` relies on against a real CDN.
 */
function rangeFetch(): typeof fetch {
  return (async (_url: string, init?: RequestInit) => {
    const range = (init?.headers as Record<string, string>)?.Range;
    const m = /bytes=(\d+)-(\d+)/.exec(range ?? '');
    if (!m) {
      return { ok: true, status: 200, statusText: 'OK', arrayBuffer: async () => bufferToArrayBuffer(FIXTURE_BYTES) };
    }
    const start = Number(m[1]);
    const end = Math.min(Number(m[2]), FIXTURE_BYTES.length - 1);
    const slice = FIXTURE_BYTES.subarray(start, end + 1);
    return {
      ok: true,
      status: 206,
      statusText: 'Partial Content',
      arrayBuffer: async () => bufferToArrayBuffer(slice),
    };
  }) as unknown as typeof fetch;
}

function bufferToArrayBuffer(buf: Uint8Array): ArrayBuffer {
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
}

describe('STTArchive (Arrow format)', () => {
  it('reads metadata from the JSON block', async () => {
    const archive = new STTArchive({ url: 'mem://sample.stt', fetch: rangeFetch() });
    const meta = await archive.getMetadata();
    // The fixture is a v4 archive (regenerated by make_sample_fixture).
    expect(meta.version).toBe(4);
    expect(meta.minZoom).toBeLessThanOrEqual(meta.maxZoom);
    expect(meta.bounds.minLon).toBeLessThan(meta.bounds.maxLon);
    expect(meta.timeRange.end).toBeGreaterThan(meta.timeRange.start);
    expect(meta.temporalBucketMs).toBeGreaterThan(0);
  });

  it('reads the Arrow index directory', async () => {
    const archive = new STTArchive({ url: 'mem://sample.stt', fetch: rangeFetch() });
    const index = await archive.getIndex();
    expect(index.tiles.length).toBeGreaterThan(0);
    for (const t of index.tiles) {
      expect(t.length).toBeGreaterThan(0);
      expect(t.timeEnd).toBeGreaterThanOrEqual(t.timeStart);
      expect(t.featureCount).toBeGreaterThan(0);
    }
  });

  it('fetches and decodes a tile into binary features', async () => {
    const archive = new STTArchive({ url: 'mem://sample.stt', fetch: rangeFetch() });
    const index = await archive.getIndex();
    const entry = index.tiles[0];
    const tile = await archive.getTile({
      z: entry.zoom,
      x: entry.x,
      y: entry.y,
      t: entry.timeStart,
    });
    expect(tile).not.toBeNull();
    expect(tile!.layers.length).toBeGreaterThan(0);

    const features = tile!.layers[0].features;
    expect(features.featureCount).toBeGreaterThan(0);
    // Point fixtures: 2 interleaved coords per feature, no startIndices.
    expect(features.geometryType).toBe(GeometryType.Point);
    expect(features.positions.length).toBe(features.featureCount * 2);
    expect(features.featureIds.length).toBe(features.featureCount);
    expect(features.startTimes.length).toBe(features.featureCount);

    // Coordinates are real WGS84 lon/lat near the fixture's San Francisco box.
    for (let i = 0; i < features.positions.length; i += 2) {
      expect(features.positions[i]).toBeGreaterThan(-123);
      expect(features.positions[i]).toBeLessThan(-121);
      expect(features.positions[i + 1]).toBeGreaterThan(37);
      expect(features.positions[i + 1]).toBeLessThan(39);
    }

    // The fixture carries a numeric `speed` and categorical `kind` column.
    expect(features.numericProps.speed).toBeDefined();
    expect(features.numericProps.speed.length).toBe(features.featureCount);
    expect(features.categoricalProps.kind).toBeDefined();
    expect(features.categoricalProps.kind.categories.length).toBeGreaterThan(0);

    // Regression: the dictionary decoder used to treat Arrow's empty
    // `nullBitmap` (returned for null-free columns) as "all rows null",
    // marking every index with the 0xffff sentinel. Downstream consumers
    // (e.g. HeatmapTimeLayer's categoryFilter) then dropped every feature
    // and the layer rendered nothing. Assert that at least one feature has
    // a real, in-range dictionary index — not the null sentinel.
    const kindIdx = features.categoricalProps.kind.indices;
    const numCats = features.categoricalProps.kind.categories.length;
    let resolved = 0;
    for (let i = 0; i < kindIdx.length; i++) {
      if (kindIdx[i] !== 0xffff) {
        expect(kindIdx[i]).toBeLessThan(numCats);
        resolved++;
      }
    }
    expect(resolved).toBeGreaterThan(0);
  });

  it('serves repeated tile reads from the byte cache', async () => {
    const archive = new STTArchive({ url: 'mem://sample.stt', fetch: rangeFetch() });
    const index = await archive.getIndex();
    const e = index.tiles[0];
    const id = { z: e.zoom, x: e.x, y: e.y, t: e.timeStart };
    await archive.getTile(id);
    await archive.getTile(id);
    const stats = archive.getCacheStats();
    expect(stats.hits).toBeGreaterThanOrEqual(1);
  });

  it('returns null for a tile that is not in the directory', async () => {
    const archive = new STTArchive({ url: 'mem://sample.stt', fetch: rangeFetch() });
    const tile = await archive.getTile({ z: 20, x: 1, y: 1, t: 0 });
    expect(tile).toBeNull();
  });

  it('honours coalesceGapBytes and maxConcurrentRequests over many non-adjacent blobs', async () => {
    // The committed fixture has a single tile, so synthesize a multi-blob
    // archive by replicating the fixture's real (decodable) blob K times with
    // PADDING between copies — non-adjacent on disk so a zero gap does NOT
    // coalesce them, but an unbounded gap merges all K into one range request.
    const fixtureIdx = await new STTArchive({ url: 'mem://s.stt', fetch: rangeFetch() }).getIndex();
    const e = fixtureIdx.tiles[0];
    const blob = FIXTURE_BYTES.subarray(e.offset, e.offset + e.length);
    const compressionByte = FIXTURE_BYTES[5];
    // Header fields of the fixture (little-endian u64s start at byte 6).
    const hv = new DataView(bufferToArrayBuffer(FIXTURE_BYTES));
    const metaOff = Number(hv.getBigUint64(22, true));
    const metaLen = Number(hv.getBigUint64(30, true));
    const metaBytes = FIXTURE_BYTES.subarray(metaOff, metaOff + metaLen);

    const K = 6;
    const PAD = 4096;
    const stride = e.length + PAD;
    const entries = Array.from({ length: K }, (_, i) => ({
      zoom: e.zoom, x: e.x, y: e.y,
      timeStart: i, timeEnd: i,
      offset: HEADER_SIZE + i * stride,
      length: e.length,
      uncompressedSize: e.uncompressedSize,
      featureCount: e.featureCount,
      hilbert: i,
      crc32c: i + 1,
      temporalBucketMs: e.temporalBucketMs,
    }));
    const dir = encodeDirectory(entries);
    const indexOffset = HEADER_SIZE + (K - 1) * stride + e.length;
    const metadataOffset = indexOffset + dir.length;
    const total = metadataOffset + metaBytes.length;

    const buf = new Uint8Array(total);
    buf.set([0x53, 0x54, 0x54, 0x04], 0); // "STT" + v4
    buf[4] = 4;
    buf[5] = compressionByte;
    const dv = new DataView(buf.buffer);
    dv.setBigUint64(6, BigInt(indexOffset), true);
    dv.setBigUint64(14, BigInt(dir.length), true);
    dv.setBigUint64(22, BigInt(metadataOffset), true);
    dv.setBigUint64(30, BigInt(metaBytes.length), true);
    for (let i = 0; i < K; i++) buf.set(blob, HEADER_SIZE + i * stride);
    buf.set(dir, indexOffset);
    buf.set(metaBytes, metadataOffset);

    function countingFetch(state: { calls: number; inFlight: number; peak: number }): typeof fetch {
      return (async (_url: string, init?: RequestInit) => {
        const m = /bytes=(\d+)-(\d+)/.exec((init?.headers as Record<string, string>)?.Range ?? '');
        state.calls++; state.inFlight++; state.peak = Math.max(state.peak, state.inFlight);
        await new Promise((r) => setTimeout(r, 1));
        state.inFlight--;
        const start = Number(m![1]);
        const end = Math.min(Number(m![2]), buf.length - 1);
        const slice = buf.subarray(start, end + 1);
        return { ok: true, status: 206, statusText: 'Partial Content', arrayBuffer: async () => bufferToArrayBuffer(slice) };
      }) as unknown as typeof fetch;
    }

    const tileIds = entries.map((en) => ({ z: en.zoom, x: en.x, y: en.y, t: en.timeStart }));

    // Unbounded gap → all K blobs coalesce into ONE tile range request.
    const wide = { calls: 0, inFlight: 0, peak: 0 };
    const aWide = new STTArchive({ url: 'mem://m.stt', fetch: countingFetch(wide), coalesceGapBytes: Number.MAX_SAFE_INTEGER });
    await aWide.getIndex();
    const wideBefore = wide.calls;
    const tilesWide = await aWide.getTiles(tileIds);
    expect(tilesWide.every((t) => t !== null)).toBe(true);
    expect(wide.calls - wideBefore).toBe(1);

    // Zero gap → K separate requests, but never more than maxConcurrentRequests
    // in flight at once.
    const tight = { calls: 0, inFlight: 0, peak: 0 };
    const aTight = new STTArchive({ url: 'mem://m.stt', fetch: countingFetch(tight), coalesceGapBytes: 0, maxConcurrentRequests: 2 });
    await aTight.getIndex();
    const tightBefore = tight.calls;
    const tilesTight = await aTight.getTiles(tileIds);
    expect(tilesTight.every((t) => t !== null)).toBe(true);
    expect(tight.calls - tightBefore).toBe(K);
    expect(tight.peak).toBeLessThanOrEqual(2);
  });

  it('rejects a server that ignores Range requests', async () => {
    const badFetch = (async () => ({
      ok: true,
      status: 200,
      statusText: 'OK',
      arrayBuffer: async () => bufferToArrayBuffer(FIXTURE_BYTES),
    })) as unknown as typeof fetch;
    const archive = new STTArchive({ url: 'mem://sample.stt', fetch: badFetch });
    await expect(archive.getMetadata()).rejects.toThrow(/Range/);
  });
});
