#!/bin/bash
# Quick reference for common AIS data generation tasks

echo "🚢 AIS Data Generation Quick Reference"
echo "======================================"
echo ""
echo "Available Commands:"
echo ""
echo "1. Generate 7 days for San Francisco Bay (default)"
echo "   ./generate-ais-sf-week.sh"
echo ""
echo "2. Interactive multi-day processor (choose region and days)"
echo "   ./process-ais-multi-day.sh"
echo ""
echo "3. Process single CSV file"
echo "   ../../target/release/generate-ais-data \\"
echo "     --input data/marineCadastre/AIS_2023_01_01.csv \\"
echo "     --output data/output.geojson \\"
echo "     --sample-minutes 10 \\"
echo "     --bounds \"36.5,-123.5,38.5,-121.5\" \\"
echo "     --max-vessels 3000"
echo ""
echo "4. Build STT archive from GeoJSON"
echo "   ../../target/release/stt-build \\"
echo "     --input data/output.geojson \\"
echo "     --output ../../examples/showcase/public/data/output.stt \\"
echo "     --time-field timestamp \\"
echo "     --temporal-resolution high-frequency \\"
echo "     --min-zoom 0 \\"
echo "     --max-zoom 14 \\"
echo "     --compression gzip"
echo ""
echo "Common Geographic Bounds:"
echo "  • San Francisco Bay:     36.5,-123.5,38.5,-121.5"
echo "  • Los Angeles/Long Beach: 33.0,-119.0,34.0,-117.5"
echo "  • Seattle/Puget Sound:    47.0,-123.0,48.5,-122.0"
echo "  • Gulf of Mexico:         25.0,-97.0,30.0,-80.0"
echo "  • US East Coast:          25.0,-80.0,45.0,-65.0"
echo ""
echo "Sample Rates:"
echo "  • High frequency (5 min):   --sample-minutes 5"
echo "  • Medium frequency (10 min): --sample-minutes 10  [default]"
echo "  • Low frequency (15 min):    --sample-minutes 15"
echo "  • Hourly:                    --sample-minutes 60"
echo ""
echo "Dataset Sizes (approximate):"
echo "  • 1 day, SF Bay, 10min sampling:    ~15 MB GeoJSON → ~60 MB STT"
echo "  • 7 days, SF Bay, 10min sampling:   ~62 MB GeoJSON → ~440 MB STT"
echo "  • 1 day, Full US, 10min sampling:   ~200 MB GeoJSON → ~1.5 GB STT"
echo ""
echo "Troubleshooting:"
echo "  • Out of memory? Reduce --max-vessels or --sample-minutes"
echo "  • Too large? Increase --sample-minutes or reduce date range"
echo "  • No data? Check --bounds coordinates (lon,lat order)"
echo ""
echo "Documentation:"
echo "  • Full guide: AIS_DATA_GENERATION_SUMMARY.md"
echo "  • Data source info: data/marineCadastre/README.md"
echo "  • Main docs: ../../README.md"
echo ""




