#!/usr/bin/env python3
"""Emit ``docs/spec/av-palettes.json`` — the AV cockpit's cross-language palette contract.

The AV palettes were a hand-maintained DUAL COPY: the authoritative values in
``av_common.py`` (baked into scene.json and the tiles), and a second copy in the
renderer's ``examples/showcase/src/datasets.ts`` (rendered geometry and legend).
They were kept in lockstep by a comment, and the pair had already drifted in hue
once before anyone noticed, so ``test_av_palette_parity.py`` was written to read
BOTH files and assert they agreed.

That test cannot survive the repository split — the two files no longer share a
tree (docs/roadmap/repo-split-2026-08.md §4.3). What replaces it is this file:
the Python side, which is the authority, EXPORTS the contract as a checked-in
artifact, and each side then asserts against the artifact rather than against
the other's source. The renderer gets a file it can read with `JSON.parse`
instead of a regex over TypeScript, and — more usefully — so does anyone else
building an AV cockpit against these archives.

Two kinds of obligation are exported, matching what the old test enforced:

* ``valueLocked`` — key-set AND RGBA per key must match (``OBJECT_COLORS``,
  ``LIDARSEG_COLORS``, ``HEIGHT_BAND_COLORS``).
* ``keySets`` — only the names are the contract, because the colours live on the
  renderer side alone: ``MAP_LAYERS`` (the valid ``map_layer`` strings the
  extractors emit; unordered) and ``ISO_DENSITY_BANDS`` (ordered — the band
  order is the ramp order).

``tsOnlyKeys`` records the one documented exception: ``ego``, a synthetic
ego-track colour that exists only in the renderer.

Usage:
  python emit_av_palettes.py            # rewrite the artifact
  python emit_av_palettes.py --check    # byte-compare, write nothing (CI gate)
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import av_common as avc

_REPO_ROOT = Path(__file__).resolve().parents[2]
_ARTIFACT = _REPO_ROOT / "docs" / "spec" / "av-palettes.json"


def _rgba(value) -> list[int]:
    out = [int(x) for x in value]
    assert len(out) == 4, f"expected RGBA (4 ints), got {value!r}"
    return out


def build() -> str:
    doc = {
        "$comment": (
            "GENERATED by scripts/data-generation/emit_av_palettes.py from "
            "av_common.py — do not hand-edit. The AV cockpit's cross-language "
            "palette contract: the extractors bake these values into scene.json "
            "and the tiles, and any renderer drawing those archives must paint "
            "them identically. See docs/roadmap/av-cockpit.md §2 and "
            "docs/spec/sidecar-assets.md."
        ),
        "version": 1,
        "valueLocked": {
            "OBJECT_COLORS": {k: _rgba(v) for k, v in sorted(avc.OBJECT_COLORS.items())},
            "LIDARSEG_COLORS": {
                k: _rgba(v) for k, v in sorted(avc.LIDARSEG_COLORS.items())
            },
            "HEIGHT_BAND_COLORS": {
                k: _rgba(v) for k, v in avc.HEIGHT_BAND_COLORS.items()
            },
        },
        "keySets": {
            # Unordered: this is a validity set for the `map_layer` column.
            "MAP_LAYERS": sorted(avc.MAP_LAYERS),
            # ORDERED: band order is ramp order, and the legend must follow it.
            "ISO_DENSITY_BANDS": list(avc.ISO_DENSITY_BANDS),
        },
        "tsOnlyKeys": {"OBJECT_COLORS": ["ego"]},
    }
    text = json.dumps(doc, indent=2, ensure_ascii=False)
    # Collapse the RGBA / string arrays onto one line each. `indent=2` splits
    # every array element onto its own line, which turns a 28-palette artifact
    # into 500 lines and makes a one-channel change unreadable in review.
    text = re.sub(
        r"\[\s*\n\s*((?:[^][{}]|\n)*?)\n\s*\]",
        lambda m: "[" + " ".join(part.strip() for part in m.group(1).split("\n")) + "]",
        text,
    )
    return text + "\n"


def main(argv: list[str]) -> int:
    want = build()
    if "--check" in argv:
        if not _ARTIFACT.is_file():
            print(f"FAIL: {_ARTIFACT} does not exist — run without --check")
            return 1
        have = _ARTIFACT.read_text()
        if have != want:
            print(
                f"FAIL: {_ARTIFACT.relative_to(_REPO_ROOT)} is stale.\n"
                "  av_common.py's palettes changed without regenerating the "
                "artifact. Run:\n"
                "    python scripts/data-generation/emit_av_palettes.py"
            )
            return 1
        print(f"av-palettes.json matches av_common.py ({len(want)} bytes)")
        return 0
    _ARTIFACT.write_text(want)
    print(f"wrote {_ARTIFACT.relative_to(_REPO_ROOT)} ({len(want)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
