#!/usr/bin/env node
/**
 * Build script to bundle the STT decoder worker with all its dependencies.
 * This creates a self-contained worker file that works in production deployments.
 */

import * as esbuild from 'esbuild';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';
import { readFileSync, writeFileSync, mkdirSync } from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = resolve(__dirname, '..');

async function buildWorker() {
  console.log('Building STT decoder worker...');
  
  const workerEntry = resolve(rootDir, 'src/workers/stt-decoder.worker.ts');
  const outDir = resolve(rootDir, 'dist/workers');
  
  // Ensure output directory exists
  mkdirSync(outDir, { recursive: true });
  
  try {
    // Bundle the worker with all dependencies
    const result = await esbuild.build({
      entryPoints: [workerEntry],
      bundle: true,
      format: 'esm',
      target: 'es2020',
      platform: 'browser',
      outfile: resolve(outDir, 'stt-decoder.worker.bundled.js'),
      minify: true,
      sourcemap: true,
      // Don't externalize anything - bundle everything into the worker
      external: [],
      // Define globals that might be needed
      define: {
        'process.env.NODE_ENV': '"production"',
      },
    });
    
    if (result.errors.length > 0) {
      console.error('Build errors:', result.errors);
      process.exit(1);
    }
    
    console.log('✓ Worker bundled successfully: dist/workers/stt-decoder.worker.bundled.js');
    
    // Also generate an inline version as a fallback
    const bundledCode = readFileSync(resolve(outDir, 'stt-decoder.worker.bundled.js'), 'utf-8');
    const base64Code = Buffer.from(bundledCode).toString('base64');
    
    // JavaScript version (no TypeScript syntax)
    const inlineWorkerModule = `/**
 * Inline worker code for environments where external worker files don't work.
 * Auto-generated by scripts/build-worker.mjs - DO NOT EDIT
 */
export const WORKER_CODE_BASE64 = "${base64Code}";

export function createWorkerBlob() {
  const code = atob(WORKER_CODE_BASE64);
  return new Blob([code], { type: 'application/javascript' });
}

export function createWorkerURL() {
  return URL.createObjectURL(createWorkerBlob());
}
`;
    
    writeFileSync(resolve(outDir, 'inline-worker.js'), inlineWorkerModule);
    
    // Generate TypeScript declaration
    const inlineWorkerDts = `/**
 * Inline worker code for environments where external worker files don't work.
 * Auto-generated by scripts/build-worker.mjs - DO NOT EDIT
 */
export declare const WORKER_CODE_BASE64: string;
export declare function createWorkerBlob(): Blob;
export declare function createWorkerURL(): string;
`;
    
    writeFileSync(resolve(outDir, 'inline-worker.d.ts'), inlineWorkerDts);
    
    console.log('✓ Inline worker module generated: dist/workers/inline-worker.js');
    
  } catch (error) {
    console.error('Failed to build worker:', error);
    process.exit(1);
  }
}

buildWorker();

