//! Golden byte-stability pin for the **manifest formatVersion 2** writer — the
//! CURRENT DEFAULT emission (design notes:
//! `docs/roadmap/stt-packed-format-decisions.md`).
//!
//! THE CONTRACT: formatVersion 2 is the ONLY emission `stt-build` writes, so it
//! is what every published archive, every content-addressed pack name, and
//! every edge cache key is built on. This file pins it with a committed fixture
//! corpus under `tests/fixtures/v2-golden/` that the current writer MUST keep
//! reproducing byte-for-byte — every object AND the manifest (whose
//! formatVersion-2 `schemas` template table is part of the pin).
//!
//! Why a BYTE pin when formatVersion 2 is not frozen: the other coverage is
//! *decode-equivalence* (`packages/core/test/fixtures/v2-golden*`, generated by
//! `packages/core/scripts/make-v2-golden.sh`, asserted by the TS reader) and
//! *rebuild-determinism* (`reproducible_build.rs`
//! `v2_dataset_rebuild_is_byte_identical_including_schemas`, which compares two
//! builds of the SAME binary against each other). Neither notices an encoder
//! change that still decodes fine and is still self-consistent — a reordered
//! pack layout, a different zstd level, a dropped schema-metadata key, a
//! template-hoist tweak. Those silently re-address every object: identical
//! pixels, a wholly new pack fleet, and a cold cache on every deploy. Only a
//! committed corpus catches it, which is what this file is.
//!
//! formatVersion 2 is NOT frozen — an intentional format change is allowed. The pin's job is
//! to make such a change *deliberate and reviewed* (regenerate the fixture in
//! the same commit, and expect the diff to show every object address churning)
//! rather than accidental.
//!
//! Two datasets cover both directory container shapes the writer emits:
//!   * `single/` — whole-load v5 directory.
//!   * `paged/`  — root + leaf pages (`with_paging`).
//!
//! Tile content: a quantized point layer (coord quant + range-adaptive attr
//! quant → per-tile `stt:qa` / `stt:quant` metadata), a categorical property
//! (dictionary column), a trajectory layer with u16-delta `vertex_time`, and an
//! empty-bucket tile. All of it at the encoder defaults, so the compact time
//! shape (`TILE_META.st`/`et`) is exercised too — and the empty tile, which
//! keeps the absolute pair, is what mints the extra CORE template in
//! `manifest.schemas`. That per-tile-varying metadata is exactly what the
//! schema-template hoist must keep OUT of the shared `manifest.schemas`
//! entries — so the manifest bytes are the load-bearing part of this pin, not
//! an incidental one.
//!
//! `expected-hashes.json` records the blake3-128 of every object so drift is
//! reported by name even when a byte-diff would be opaque.
//!
//! Regenerate (ONLY alongside an intentional, reviewed change to formatVersion-2
//! emission —
//! regenerating REPLACES the pin):
//!   cargo test -p stt-core --test v2_golden -- --ignored regenerate_v2_golden

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use stt_core::arrow_tile::{
    encode_tile_with, ColumnarLayer, EncoderConfig, GeometryColumn, PropertyColumn,
};
use stt_core::metadata::Metadata;
use stt_core::pack::{CAPABILITY_ATTR_QUANT, CAPABILITY_COORD_QUANT, CAPABILITY_TIME_DELTA};
use stt_core::{BlobOrdering, PackWriter, TileId};

/// blake3 content address, 128-bit → 32 lowercase hex chars (the packed
/// format's object-address convention).
fn blake3_128_hex(bytes: &[u8]) -> String {
    blake3::hash(bytes).as_bytes()[..16]
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

fn fixture_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("v2-golden")
}

/// The production-like encoder settings the fixture pins: world-grid coordinate
/// quantization at 1 m + range-adaptive UInt16 attribute quantization, on layer
/// frames feeding the writer's template collector. This is the config that makes
/// `stt:qa` / `stt:time_offset_ms` per-tile-varying — the exact variance the
/// schema-template hoist must strip out of `manifest.schemas` while leaving each
/// frame decodable, so pinning it pins the hoist.
fn golden_encoder_config(writer: &PackWriter) -> EncoderConfig {
    EncoderConfig {
        quantize_coords_m: Some(1.0),
        quantize_attrs_auto: true,
        // Explicit (even though it's the default): the frames must stay at the
        // current layer-frame version, and
        // must reference templates through the WRITER's collector — a frame
        // whose template never reaches `manifest.schemas` is undecodable.
        format_version: stt_core::arrow_tile::LAYER_FRAME_VERSION,
        template_collector: Some(writer.template_collector()),
        ..EncoderConfig::default()
    }
}

/// Quantized point layer: numeric `speed` (with a null) + categorical `kind`
/// (with a null). `seed` shifts ids/times/values so distinct tiles get
/// distinct `stt:qa` affines and `stt:time_offset_ms` origins.
fn point_layer(seed: u64, n: usize) -> ColumnarLayer {
    let base = 1_700_000_000_000i64 + seed as i64 * 3_600_000;
    let cats = ["car", "bus", "tram"];
    ColumnarLayer {
        polygon_parts: None,
        name: "default".to_string(),
        feature_ids: (0..n as u64).map(|i| seed * 1000 + i).collect(),
        start_times: (0..n as i64).map(|i| base + i * 1000).collect(),
        end_times: (0..n as i64).map(|i| base + i * 1000 + 60_000).collect(),
        geometry: GeometryColumn::Point(
            (0..n)
                .map(|i| {
                    [
                        -122.4 + seed as f64 * 0.01 + i as f64 * 1e-4,
                        37.7 + i as f64 * 5e-5,
                    ]
                })
                .collect(),
        ),
        vertex_times: None,
        vertex_values: None,
        triangles: None,
        vertex_value_matrix: None,
        properties: vec![
            (
                "speed".to_string(),
                PropertyColumn::Numeric(
                    (0..n)
                        .map(|i| {
                            if i == 1 {
                                None
                            } else {
                                Some(seed as f64 * 7.5 + i as f64 * 3.25)
                            }
                        })
                        .collect(),
                ),
            ),
            (
                "kind".to_string(),
                PropertyColumn::Categorical(
                    (0..n)
                        .map(|i| {
                            if i == 2 {
                                None
                            } else {
                                Some(cats[i % cats.len()].to_string())
                            }
                        })
                        .collect(),
                ),
            ),
        ],
    }
}

/// Trajectory layer with a tight per-vertex time span → the u16-delta
/// `vertex_time` encoding (per-layer origin/step in schema metadata).
fn trajectory_layer() -> ColumnarLayer {
    let base = 1_700_003_600_000i64;
    ColumnarLayer {
        polygon_parts: None,
        name: "tracks".to_string(),
        feature_ids: vec![9001, 9002],
        start_times: vec![base, base + 5_000],
        end_times: vec![base + 30_000, base + 42_000],
        geometry: GeometryColumn::LineString(vec![
            vec![[-122.40, 37.70], [-122.41, 37.71], [-122.42, 37.72]],
            vec![[-122.50, 37.75], [-122.51, 37.76]],
        ]),
        vertex_times: Some(vec![
            vec![base, base + 15_000, base + 30_000],
            vec![base + 5_000, base + 42_000],
        ]),
        vertex_values: None,
        triangles: None,
        vertex_value_matrix: None,
        properties: vec![(
            "speed".to_string(),
            PropertyColumn::Numeric(vec![Some(12.5), Some(30.0)]),
        )],
    }
}

/// Empty-bucket tile: zero rows, but the full column set (numeric +
/// categorical) — a dictionary column at n=0 still carries a DictionaryBatch.
fn empty_layer() -> ColumnarLayer {
    ColumnarLayer {
        polygon_parts: None,
        name: "default".to_string(),
        feature_ids: vec![],
        start_times: vec![],
        end_times: vec![],
        geometry: GeometryColumn::Point(vec![]),
        vertex_times: None,
        vertex_values: None,
        triangles: None,
        vertex_value_matrix: None,
        properties: vec![
            ("speed".to_string(), PropertyColumn::Numeric(vec![])),
            ("kind".to_string(), PropertyColumn::Categorical(vec![])),
        ],
    }
}

/// Build one golden dataset (single or paged directory) into `out`.
///
/// Everything is deterministic: fixed payload content, `SpatialMajor` ordering
/// (independent of the Auto heuristic), fixed pack target, default zstd level.
///
/// The writer is created FIRST because a layer frame references its schema
/// template by hash: the encoder needs the writer's collector before
/// the first `encode_tile_with` or the template never lands in `manifest.schemas`
/// and the archive decodes to nothing.
fn build_v2_dataset(out: &Path, paging: Option<usize>) -> stt_core::Manifest {
    let bucket = 3_600_000i64;
    let t0 = 1_700_000_000_000i64 - 1_700_000_000_000i64 % bucket;

    let mut writer = PackWriter::create(out, BlobOrdering::SpatialMajor, 4 * 1024)
        .unwrap()
        .with_paging(paging)
        .with_capabilities(vec![
            CAPABILITY_COORD_QUANT.to_string(),
            CAPABILITY_ATTR_QUANT.to_string(),
            // The encoder config below leaves `compact_times` at its default
            // (on), so these frames carry `TILE_META.st`/`et` — a shape a
            // reader must understand to reconstruct absolute times. Declaring
            // it keeps the fixture a CONFORMANT archive, matching what
            // `stt-build`'s `required_capabilities()` emits; a fixture that
            // used the shape without declaring it would pin a spec violation.
            CAPABILITY_TIME_DELTA.to_string(),
        ]);
    // The pin is on the DEFAULT emission — formatVersion 2 is not requested
    // here, it is what
    // an unconfigured writer produces. If the default ever moves, this fires
    // with a readable message instead of a wall of byte diffs.
    assert_eq!(
        writer.format_version(),
        stt_core::pack::PACKED_FORMAT_VERSION,
        "the golden corpus pins the writer's DEFAULT emission"
    );
    let cfg = golden_encoder_config(&writer);

    // (id, time_start, time_end, feature_count, payload)
    let mut tiles: Vec<(TileId, i64, i64, u32, Vec<u8>)> = Vec::new();
    // Quantized point tiles across a few cells/buckets (distinct qa/t0 per tile).
    for k in 0..4u64 {
        let layer = point_layer(k, 5);
        let ts = t0 + (k as i64 % 2) * bucket;
        let payload = encode_tile_with(std::slice::from_ref(&layer), &cfg).unwrap();
        tiles.push((
            TileId::new(5, 5 + k as u32, 11, ts.max(0) as u64),
            ts,
            ts + bucket - 1,
            5,
            payload,
        ));
    }
    // Trajectory tile (vertex_time u16-delta path).
    let traj = encode_tile_with(&[trajectory_layer()], &cfg).unwrap();
    tiles.push((
        TileId::new(5, 9, 11, t0.max(0) as u64),
        t0,
        t0 + bucket - 1,
        2,
        traj,
    ));
    // Empty-bucket tile.
    let empty = encode_tile_with(&[empty_layer()], &cfg).unwrap();
    tiles.push((
        TileId::new(5, 10, 11, (t0 + bucket).max(0) as u64),
        t0 + bucket,
        t0 + 2 * bucket - 1,
        0,
        empty,
    ));

    for (id, ts, te, n, payload) in &tiles {
        writer
            .add_tile_full(id, *ts, *te, Some(*ts), *n, Some(bucket as u64), payload)
            .unwrap();
    }
    let meta = Metadata::new("v2-golden")
        .with_description("Default formatVersion-2 byte-identity fixture")
        .with_zoom_levels(5, 5)
        .with_temporal_bucket_ms(bucket as u64)
        .with_time_range(stt_core::types::TimeRange::new(
            t0 as u64,
            (t0 + 2 * bucket - 1) as u64,
        ));
    writer.finalize(&meta).unwrap()
}

/// Recursively collect `relative path → file bytes` for a dataset directory.
fn collect_files(root: &Path) -> BTreeMap<String, Vec<u8>> {
    fn walk(root: &Path, dir: &Path, out: &mut BTreeMap<String, Vec<u8>>) {
        for entry in fs::read_dir(dir).unwrap() {
            let path = entry.unwrap().path();
            if path.is_dir() {
                walk(root, &path, out);
            } else {
                let rel = path
                    .strip_prefix(root)
                    .unwrap()
                    .components()
                    .map(|c| c.as_os_str().to_string_lossy())
                    .collect::<Vec<_>>()
                    .join("/");
                out.insert(rel, fs::read(&path).unwrap());
            }
        }
    }
    let mut out = BTreeMap::new();
    walk(root, root, &mut out);
    out
}

/// Both dataset shapes, keyed by fixture subdirectory.
fn dataset_shapes() -> [(&'static str, Option<usize>); 2] {
    [("single", None), ("paged", Some(3))]
}

/// The formatVersion-2 writer reproduces the committed golden corpus
/// byte-for-byte: every
/// object file AND the manifest, plus the recorded blake3 of each object.
#[test]
fn v2_build_is_byte_identical_to_golden() {
    let fixture_root = fixture_dir();
    assert!(
        fixture_root.exists(),
        "missing fixture {} — the committed golden corpus pins the current \
         writer's DEFAULT (formatVersion-2) emission; regenerate ONLY alongside \
         an intentional, reviewed format change (see the header comment)",
        fixture_root.display()
    );
    let expected_hashes: BTreeMap<String, String> =
        serde_json::from_slice(&fs::read(fixture_root.join("expected-hashes.json")).unwrap())
            .unwrap();

    let tmp = tempfile::tempdir().unwrap();
    let mut rebuilt_hashes: BTreeMap<String, String> = BTreeMap::new();
    for (name, paging) in dataset_shapes() {
        let out = tmp.path().join(name);
        let manifest = build_v2_dataset(&out, paging);
        // A formatVersion-2 manifest with no templates would mean the frames
        // fell back to inline schemas — the fixture would then pin un-hoisted
        // output under a formatVersion-2 label and never notice a hoist
        // regression.
        assert!(
            !manifest.schemas.is_empty(),
            "[{name}] formatVersion-2 manifest must carry schema templates"
        );

        let golden = collect_files(&fixture_root.join(name));
        let rebuilt = collect_files(&out);
        assert_eq!(
            golden.keys().collect::<Vec<_>>(),
            rebuilt.keys().collect::<Vec<_>>(),
            "[{name}] object set drifted from the golden fixture"
        );
        for (rel, bytes) in &rebuilt {
            assert_eq!(
                golden.get(rel).unwrap(),
                bytes,
                "[{name}] {rel}: bytes differ from the golden fixture — the \
                 DEFAULT emission re-addressed every object it touches (new pack \
                 names, cold edge caches, a full re-upload). If the change is \
                 intentional, regenerate the fixture in the SAME commit; if not, \
                 this is the encoder drift the pin exists to catch"
            );
            rebuilt_hashes.insert(format!("{name}/{rel}"), blake3_128_hex(bytes));
        }
    }
    assert_eq!(
        expected_hashes, rebuilt_hashes,
        "recorded blake3 pins drifted from the rebuilt datasets"
    );
}

/// The fixture is a real archive, not just bytes: it opens through the packed
/// reader and every tile decodes via the manifest's template registry. Without
/// this, a regenerated-but-broken fixture would still "pass" the byte pin
/// (it would be pinning garbage).
///
/// It also pins the one thing the byte comparison structurally cannot: that the
/// wire's COMPACT time shape (`TILE_META.st`/`et` — u32 offsets from `t0` and
/// u32 durations, or an omitted `end_time` entirely) is fully re-inflated on
/// the way out. Every decoded layer must present the same non-null absolute
/// `Int64` start/end pair a reader has always seen, with the exact millisecond
/// values the encoder was handed. If the re-inflate regresses, the archive
/// still decodes — it just silently reports times near zero — so only an
/// explicit value assertion catches it.
#[test]
fn v2_golden_fixture_decodes_through_the_reader() {
    use arrow::array::{Array, Int64Array};
    use arrow::datatypes::DataType;

    let fixture_root = fixture_dir();
    for (name, _) in dataset_shapes() {
        let manifest_path = fixture_root.join(name).join("manifest.json");
        let reader = stt_core::PackedReader::open(&manifest_path)
            .unwrap_or_else(|e| panic!("[{name}] open golden fixture: {e}"));
        assert_eq!(
            reader.format_version(),
            2,
            "[{name}] fixture must declare formatVersion 2"
        );
        let registry = reader
            .templates()
            .unwrap_or_else(|| panic!("[{name}] formatVersion-2 fixture must expose a registry"));
        let mut rows = 0usize;
        let mut min_start = i64::MAX;
        for entry in reader.entries() {
            let payload = reader
                .read_payload(entry)
                .unwrap_or_else(|e| panic!("[{name}] {:?} payload: {e}", entry.tile_id()));
            let layers = stt_core::arrow_tile::decode_tile_with_templates(&payload, registry)
                .unwrap_or_else(|e| panic!("[{name}] {:?} decode: {e}", entry.tile_id()));
            rows += layers.iter().map(|l| l.batch.num_rows()).sum::<usize>();

            for layer in &layers {
                for col in ["start_time", "end_time"] {
                    let field = layer
                        .batch
                        .schema()
                        .field_with_name(col)
                        .unwrap_or_else(|_| panic!("[{name}] layer '{}' has no {col}", layer.name))
                        .clone();
                    assert_eq!(
                        field.data_type(),
                        &DataType::Int64,
                        "[{name}] layer '{}': {col} must decode as absolute Int64, \
                         not the compact wire width",
                        layer.name
                    );
                    let arr = layer.batch.column_by_name(col).unwrap();
                    assert_eq!(
                        arr.null_count(),
                        0,
                        "[{name}] layer '{}': {col} must be non-null",
                        layer.name
                    );
                    let times = arr.as_any().downcast_ref::<Int64Array>().unwrap();
                    for i in 0..times.len() {
                        let v = times.value(i);
                        if col == "start_time" {
                            min_start = min_start.min(v);
                        }
                        // A failed re-inflate leaves raw offsets (0-ish) or raw
                        // durations here; every real feature in this corpus is
                        // anchored at/after the 2023-11-14 base.
                        assert!(
                            v >= 1_700_000_000_000,
                            "[{name}] layer '{}': {col}[{i}] = {v} is not an absolute \
                             Unix-ms timestamp — the compact-time re-inflate regressed",
                            layer.name
                        );
                    }
                }
            }
        }
        // 4 point tiles × 5 + 1 trajectory tile × 2 + 1 empty tile × 0.
        assert_eq!(rows, 22, "[{name}] decoded feature total");
        // `point_layer(0, ..)` starts exactly at the corpus base.
        assert_eq!(
            min_start, 1_700_000_000_000,
            "[{name}] earliest decoded start_time"
        );
    }
}

/// Fixture generator — regenerating REPLACES the byte pin, so run it ONLY
/// alongside an intentional, reviewed change to formatVersion-2 emission
/// (see header).
#[test]
#[ignore = "fixture regeneration replaces the formatVersion-2 byte-stability pin"]
fn regenerate_v2_golden() {
    let fixture_root = fixture_dir();
    if fixture_root.exists() {
        fs::remove_dir_all(&fixture_root).unwrap();
    }
    fs::create_dir_all(&fixture_root).unwrap();

    let mut hashes: BTreeMap<String, String> = BTreeMap::new();
    for (name, paging) in dataset_shapes() {
        let out = fixture_root.join(name);
        build_v2_dataset(&out, paging);
        for (rel, bytes) in collect_files(&out) {
            hashes.insert(format!("{name}/{rel}"), blake3_128_hex(&bytes));
        }
    }
    fs::write(
        fixture_root.join("expected-hashes.json"),
        serde_json::to_vec_pretty(&hashes).unwrap(),
    )
    .unwrap();
    println!("wrote the golden corpus to {}", fixture_root.display());
}
