//! Golden byte-stability pin for the **manifest formatVersion 3** writer — the
//! CURRENT DEFAULT emission (design notes:
//! `docs/roadmap/stt-packed-format-decisions.md`).
//!
//! THE CONTRACT: formatVersion 3 is the ONLY emission `stt-build` writes, so it
//! is what every published archive, every content-addressed pack name, and
//! every edge cache key is built on. This file pins it with a committed fixture
//! corpus under `tests/fixtures/v2-golden/` that the current writer MUST keep
//! reproducing byte-for-byte — every object AND the manifest (whose
//! formatVersion-3 `schemas` template table is part of the pin).
//!
//! Why a BYTE pin when formatVersion 3 is not frozen: the other coverage is
//! *decode-equivalence* (`packages/core/test/fixtures/v2-golden*`, generated by
//! `packages/core/scripts/make-v2-golden.sh`, asserted by the TS reader) and
//! *rebuild-determinism* (`reproducible_build.rs`
//! `v2_dataset_rebuild_is_byte_identical_including_schemas`, which compares two
//! builds of the SAME binary against each other). Neither notices an encoder
//! change that still decodes fine and is still self-consistent — a reordered
//! pack layout, a different zstd level, a dropped schema-metadata key, a
//! template-hoist tweak. Those silently re-address every object: identical
//! pixels, a wholly new pack fleet, and a cold cache on every deploy. Only a
//! committed corpus catches it, which is what this file is.
//!
//! formatVersion 3 is NOT frozen — an intentional format change is allowed. The pin's job is
//! to make such a change *deliberate and reviewed* (regenerate the fixture in
//! the same commit, and expect the diff to show every object address churning)
//! rather than accidental.
//!
//! Two datasets cover both directory container shapes the writer emits:
//!   * `single/` — whole-load v6 directory.
//!   * `paged/`  — root + leaf pages (`with_paging`).
//!
//! Tile content: a quantized point layer (coord quant + range-adaptive attr
//! quant → per-tile `stt:qa` / `stt:quant` metadata), a categorical property
//! (dictionary column), a trajectory layer with u16-delta `vertex_time`, and an
//! empty-bucket tile. All of it at the encoder defaults, so the compact time
//! shape (`TILE_META.st`/`et`) is exercised too — and the empty tile, which
//! keeps the absolute pair, is what mints the extra CORE template in
//! `manifest.schemas`. That per-tile-varying metadata is exactly what the
//! schema-template hoist must keep OUT of the shared `manifest.schemas`
//! entries — so the manifest bytes are the load-bearing part of this pin, not
//! an incidental one.
//!
//! # The corpus is built by TWO PASSES, because the encoder it pins has two
//!
//! Mechanism M2 makes the numeric affine, the dictionary-vs-`Utf8` verdict and
//! the integer leaf width functions of the DATASET rather than of whichever
//! rows a tile caught — carried into the encoder as
//! [`EncoderConfig::global_pins`]. A fixture built at `..EncoderConfig::default()`
//! leaves that field `None` and therefore encodes on the INCUMBENT per-tile
//! path: it would stay green through every byte the pinned path moves, and
//! regenerating it would re-bless unpinned bytes while pinning nothing new.
//! That is the failure this file has to avoid, so [`build_v2_dataset`] runs the
//! real shape in miniature — pass 1 derives [`golden_pins`] from the corpus's
//! own features, pass 2 encodes every tile against them — and
//! [`golden_fixture_exercises_the_pinned_path`] asserts, without reference to
//! any committed byte, that the pins actually BITE (a per-tile encode of the
//! same layer differs). If the corpus is ever shrunk or the pins unwired, that
//! test fails long before the byte pin could quietly go blind.
//!
//! The three pinned columns are chosen so each one changes something a per-tile
//! encoder would have decided differently:
//!   * `speed` (fractional) — the pinned affine is the DATASET's range, while
//!     every tile's own minimum differs, so `stt:qa` moves in every tile.
//!   * `count` (integer, dataset span > 16 bits) — pins to an `Int32` leaf,
//!     while each tile's own span fits `UInt16`. This is the §3.8 template fork
//!     made visible: one column, one realized PROPS shape.
//!   * `kind` (categorical) — pins to a dictionary against the dataset-global
//!     category list, which every tile ships IN FULL even though every tile
//!     holds a strict subset of it. The per-tile size comparison picks `Utf8`
//!     for tiles this small, so the pin flips the Arrow type outright.
//!
//! `expected-hashes.json` records the blake3-128 of every object so drift is
//! reported by name even when a byte-diff would be opaque.
//!
//! Regenerate (ONLY alongside an intentional, reviewed change to formatVersion-3
//! emission —
//! regenerating REPLACES the pin):
//!   cargo test -p stt-core --test v2_golden -- --ignored regenerate_v2_golden

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use stt_core::arrow_tile::{
    dataset_dictionary_is_smaller, encode_tile_with, AttrPinned, ColumnarLayer, EncoderConfig,
    GeometryColumn, GlobalColumnPins, GlobalDictVerdict, PinnedLeaf, PropertyColumn,
};
use stt_core::metadata::Metadata;
use stt_core::pack::{CAPABILITY_ATTR_QUANT, CAPABILITY_COORD_QUANT, CAPABILITY_TIME_DELTA};
use stt_core::{BlobOrdering, PackWriter, TileId};

/// blake3 content address, 128-bit → 32 lowercase hex chars (the packed
/// format's object-address convention).
fn blake3_128_hex(bytes: &[u8]) -> String {
    blake3::hash(bytes).as_bytes()[..16]
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

fn fixture_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("v2-golden")
}

/// The production-like encoder settings the fixture pins: world-grid coordinate
/// quantization at 1 m + range-adaptive UInt16 attribute quantization, on layer
/// frames feeding the writer's template collector, **with the dataset-global
/// pins mechanism M2 resolves in pass 1**. This is the config that makes
/// `stt:qa` / `stt:time_offset_ms` per-tile-varying — the exact variance the
/// schema-template hoist must strip out of `manifest.schemas` while leaving each
/// frame decodable, so pinning it pins the hoist.
///
/// `global_pins` is the load-bearing argument and is deliberately NOT defaulted:
/// `..EncoderConfig::default()` leaves it `None`, which routes the whole encode
/// onto the incumbent per-tile path — a corpus built that way is invisible to
/// every byte mechanism M2 moves. See the module header.
fn golden_encoder_config(writer: &PackWriter, pins: &Arc<GlobalColumnPins>) -> EncoderConfig {
    EncoderConfig {
        quantize_coords_m: Some(1.0),
        quantize_attrs_auto: true,
        // Explicit (even though it's the default): the frames must stay at the
        // current layer-frame version, and
        // must reference templates through the WRITER's collector — a frame
        // whose template never reaches `manifest.schemas` is undecodable.
        format_version: stt_core::arrow_tile::LAYER_FRAME_VERSION,
        template_collector: Some(writer.template_collector()),
        global_pins: Some(Arc::clone(pins)),
        ..EncoderConfig::default()
    }
}

// ----------------------------------------------------------------------------
// Pass 1 — the dataset-global pins, mirrored from the builder's rule
// ----------------------------------------------------------------------------

/// Category-count ceiling for a hoistable dictionary — mirrors
/// `stt_build::dataset_stats::MAX_HOISTED_CATEGORIES`.
const MAX_HOISTED_CATEGORIES: usize = 1024;
/// Category-UTF-8-byte ceiling — mirrors
/// `stt_build::dataset_stats::MAX_HOISTED_CATEGORY_BYTES`.
const MAX_HOISTED_CATEGORY_BYTES: u64 = 4096;

/// Resolve the dataset-global pins from the corpus's own features — pass 1 of
/// the two-pass build, in miniature.
///
/// This MIRRORS `stt_build::dataset_stats::DatasetStats::to_pins_with`, and is
/// repeated here for the same reason `required_capabilities` is repeated in
/// `examples/make-golden-fixture.rs`: the dependency runs `stt-build` →
/// `stt-core`, so a `stt-core` test cannot call the builder. The mirror is kept
/// THIN on purpose — every verdict below is delegated to the shared `stt-core`
/// functions the builder itself calls ([`AttrPinned::derive_auto`],
/// [`dataset_dictionary_is_smaller`]); only the ORDER of the categorical rule's
/// three tests and the two hoist caps are transcribed. If the builder's rule
/// changes, this must follow it, and the fixture's job is to make that a
/// reviewed byte movement rather than a silent one.
///
/// The one branch NOT transcribed is the distinct-set overflow
/// (`MAX_CATEGORIES = 65_536`): reproducing it would need a 65 K-category
/// fixture, and it resolves to the same `GlobalDictVerdict::Utf8` this function
/// already emits on the two size tests. It is covered by
/// `crates/stt-build/src/dataset_stats.rs`'s own unit tests.
fn golden_pins<'a>(layers: impl IntoIterator<Item = &'a ColumnarLayer>) -> GlobalColumnPins {
    let mut attr: BTreeMap<String, AttrPinned> = BTreeMap::new();
    let mut dict: BTreeMap<String, GlobalDictVerdict> = BTreeMap::new();

    // Numeric columns: the dataset's (min, max, max_abs, all_integer, finite).
    let mut numeric: BTreeMap<&str, (f64, f64, f64, bool, u64)> = BTreeMap::new();
    // Categorical columns: the first-seen global category list (the pinned
    // ordering rule, widened from per-tile to per-dataset), plus the wire-size
    // inputs. `Vec` + linear `contains`, never a `HashSet`: first-seen order is
    // part of the output and must not depend on hash iteration.
    let mut categorical: BTreeMap<&str, (Vec<String>, u64, u64)> = BTreeMap::new();

    for layer in layers {
        for (name, column) in &layer.properties {
            match column {
                PropertyColumn::Numeric(values) => {
                    let stats = numeric.entry(name.as_str()).or_insert((
                        f64::INFINITY,
                        f64::NEG_INFINITY,
                        0.0,
                        true,
                        0,
                    ));
                    for v in values.iter().flatten().copied().filter(|v| v.is_finite()) {
                        stats.0 = stats.0.min(v);
                        stats.1 = stats.1.max(v);
                        stats.2 = stats.2.max(v.abs());
                        stats.3 &= v.fract() == 0.0;
                        stats.4 += 1;
                    }
                }
                PropertyColumn::Categorical(values) => {
                    let stats = categorical
                        .entry(name.as_str())
                        .or_insert((Vec::new(), 0, 0));
                    for v in values.iter().flatten() {
                        if !stats.0.iter().any(|c| c == v) {
                            stats.0.push(v.clone());
                        }
                        stats.1 += 1;
                        stats.2 += v.len() as u64;
                    }
                }
                // Vector groups carry neither a scalar affine nor a dictionary
                // verdict, so `GlobalColumnPins` has no key for them and the
                // builder's pass-1 stats do not collect them either. The corpus
                // has none; the arm is explicit so adding one is a compile
                // error here rather than a silently unpinned column.
                PropertyColumn::Vector { .. } => {}
            }
        }
    }

    for (name, (min, max, max_abs, all_integer, finite)) in numeric {
        attr.insert(
            name.to_string(),
            AttrPinned::derive_auto(min, max, max_abs, all_integer, finite),
        );
    }
    for (name, (categories, values, total_value_bytes)) in categorical {
        let category_bytes: u64 = categories.iter().map(|c| c.len() as u64).sum();
        let k = categories.len();
        // Order matters and is the builder's: the wire test first (is the
        // dictionary the smaller form at DATASET scale, where the per-tile IPC
        // allowance is charged once rather than per tile?), then the resident
        // caps (is the hoisted list small enough to replicate into every tile
        // on the reader?).
        let verdict =
            if !dataset_dictionary_is_smaller(total_value_bytes, values, category_bytes, k as u64)
                || k > MAX_HOISTED_CATEGORIES
                || category_bytes > MAX_HOISTED_CATEGORY_BYTES
            {
                GlobalDictVerdict::Utf8
            } else {
                GlobalDictVerdict::Dictionary(Arc::new(categories))
            };
        dict.insert(name.to_string(), verdict);
    }
    GlobalColumnPins { attr, dict }
}

/// The dataset-global category list for `kind`, in the order the corpus first
/// presents them (tile seed 0 mints A and B, seed 1 mints C and D — see
/// [`TILE_KINDS`]). The pin ships THIS list, whole, in every tile.
///
/// The strings are long on purpose. The categorical verdict is a MEASUREMENT —
/// `dataset_dictionary_is_smaller` — and with three-letter categories over 16
/// cells the dictionary genuinely loses to plain `Utf8`, which would leave the
/// fixture pinning a verdict that changes nothing. At these lengths the
/// dictionary wins at dataset scale (371 B vs 576 B) while still LOSING the
/// per-tile comparison every tile makes today (279 B vs 154 B), so the pin
/// flips the Arrow type in every tile and the byte pin can see it.
/// [`golden_fixture_exercises_the_pinned_path`] asserts exactly that, so
/// shrinking the corpus below the crossover fails loudly instead of silently
/// re-blinding the fixture.
const KINDS: [&str; 4] = [
    "articulated-electric-transit-bus",
    "low-floor-light-rail-tram-vehicle",
    "harbour-passenger-ferry-vessel",
    "dockless-shared-electric-scooter",
];

/// Which two of [`KINDS`] each point tile uses. Every tile therefore holds a
/// STRICT SUBSET of the dataset-global list — the case a per-tile encoder gets
/// wrong (a tile-local dictionary per subset, one PROPS template each) and the
/// case TB-4's all-or-nothing hoist has to ship whole.
const TILE_KINDS: [[usize; 2]; 4] = [[0, 1], [2, 3], [0, 2], [1, 3]];

/// Quantized point layer: numeric `speed` (with a null), integer `count` (with
/// a null), and categorical `kind` (with a null). `seed` shifts ids/times/values
/// so distinct tiles get distinct `stt:qa` affines and `stt:time_offset_ms`
/// origins — and, for the pinned columns, so each tile's OWN verdict differs
/// from the dataset's.
fn point_layer(seed: u64, n: usize) -> ColumnarLayer {
    let base = 1_700_000_000_000i64 + seed as i64 * 3_600_000;
    let kinds = TILE_KINDS[(seed as usize) % TILE_KINDS.len()];
    ColumnarLayer {
        polygon_parts: None,
        name: "default".to_string(),
        feature_ids: (0..n as u64).map(|i| seed * 1000 + i).collect(),
        start_times: (0..n as i64).map(|i| base + i * 1000).collect(),
        end_times: (0..n as i64).map(|i| base + i * 1000 + 60_000).collect(),
        geometry: GeometryColumn::Point(
            (0..n)
                .map(|i| {
                    [
                        -122.4 + seed as f64 * 0.01 + i as f64 * 1e-4,
                        37.7 + i as f64 * 5e-5,
                    ]
                })
                .collect(),
        ),
        vertex_times: None,
        vertex_values: None,
        triangles: None,
        vertex_value_matrix: None,
        properties: vec![
            (
                "speed".to_string(),
                PropertyColumn::Numeric(
                    (0..n)
                        .map(|i| {
                            if i == 1 {
                                None
                            } else {
                                Some(seed as f64 * 7.5 + i as f64 * 3.25)
                            }
                        })
                        .collect(),
                ),
            ),
            // Integer column whose DATASET span (0..=90_003) overflows the
            // `UInt16` index space while every TILE's own span is 4. The pin
            // therefore lands on an `Int32` leaf everywhere, where a per-tile
            // encoder would pick `UInt16` in every one of these tiles — the
            // §3.8 leaf-width fork, made visible in the bytes.
            (
                "count".to_string(),
                PropertyColumn::Numeric(
                    (0..n)
                        .map(|i| {
                            if i == 4 {
                                None
                            } else {
                                Some((seed * 30_000 + i as u64) as f64)
                            }
                        })
                        .collect(),
                ),
            ),
            (
                "kind".to_string(),
                PropertyColumn::Categorical(
                    (0..n)
                        .map(|i| {
                            if i == 2 {
                                None
                            } else {
                                Some(KINDS[kinds[i % kinds.len()]].to_string())
                            }
                        })
                        .collect(),
                ),
            ),
        ],
    }
}

/// Trajectory layer with a tight per-vertex time span → the u16-delta
/// `vertex_time` encoding (per-layer origin/step in schema metadata).
fn trajectory_layer() -> ColumnarLayer {
    let base = 1_700_003_600_000i64;
    ColumnarLayer {
        polygon_parts: None,
        name: "tracks".to_string(),
        feature_ids: vec![9001, 9002],
        start_times: vec![base, base + 5_000],
        end_times: vec![base + 30_000, base + 42_000],
        geometry: GeometryColumn::LineString(vec![
            vec![[-122.40, 37.70], [-122.41, 37.71], [-122.42, 37.72]],
            vec![[-122.50, 37.75], [-122.51, 37.76]],
        ]),
        vertex_times: Some(vec![
            vec![base, base + 15_000, base + 30_000],
            vec![base + 5_000, base + 42_000],
        ]),
        vertex_values: None,
        triangles: None,
        vertex_value_matrix: None,
        properties: vec![(
            "speed".to_string(),
            PropertyColumn::Numeric(vec![Some(12.5), Some(30.0)]),
        )],
    }
}

/// Empty-bucket tile: zero rows, but the full column set (numeric +
/// categorical) — a dictionary column at n=0 still carries a DictionaryBatch.
///
/// Under the pins this tile is the sharpest case of all: with no rows there is
/// no tile-local evidence to decide anything from, so the incumbent encoder
/// degenerates (an all-null `UInt16` at `{o: 0, s: 1}`, and `Utf8` for the
/// categorical), while the pinned encoder emits the DATASET's affines and the
/// full dataset-global dictionary against zero keys. Same tile, and the whole
/// difference is which evidence the rule saw.
fn empty_layer() -> ColumnarLayer {
    ColumnarLayer {
        polygon_parts: None,
        name: "default".to_string(),
        feature_ids: vec![],
        start_times: vec![],
        end_times: vec![],
        geometry: GeometryColumn::Point(vec![]),
        vertex_times: None,
        vertex_values: None,
        triangles: None,
        vertex_value_matrix: None,
        properties: vec![
            ("speed".to_string(), PropertyColumn::Numeric(vec![])),
            ("count".to_string(), PropertyColumn::Numeric(vec![])),
            ("kind".to_string(), PropertyColumn::Categorical(vec![])),
        ],
    }
}

/// Temporal bucket the corpus is laid out on.
const BUCKET: i64 = 3_600_000;
/// Corpus time origin — the bucket floor of the 2023-11-14 base every layer
/// anchors at.
const T0: i64 = 1_700_000_000_000 - 1_700_000_000_000 % BUCKET;

/// The corpus as LAYERS, before any encoding — `(tile id, start, end, feature
/// count, layer)` in write order.
///
/// Split out so pass 1 and pass 2 read the SAME list, and so
/// [`golden_fixture_exercises_the_pinned_path`] can assert against the very
/// features the fixture is built from rather than a restatement of them. The
/// order is the encode order, which is what makes the derived dictionary's
/// first-seen ordering well defined.
fn corpus_layers() -> Vec<(TileId, i64, i64, u32, ColumnarLayer)> {
    let mut out: Vec<(TileId, i64, i64, u32, ColumnarLayer)> = Vec::new();
    // Quantized point tiles across a few cells/buckets (distinct qa/t0 per tile,
    // and — under the pins — a distinct strict subset of `KINDS` per tile).
    for k in 0..4u64 {
        let ts = T0 + (k as i64 % 2) * BUCKET;
        out.push((
            TileId::new(5, 5 + k as u32, 11, ts.max(0) as u64),
            ts,
            ts + BUCKET - 1,
            5,
            point_layer(k, 5),
        ));
    }
    // Trajectory tile (vertex_time u16-delta path).
    out.push((
        TileId::new(5, 9, 11, T0.max(0) as u64),
        T0,
        T0 + BUCKET - 1,
        2,
        trajectory_layer(),
    ));
    // Empty-bucket tile.
    out.push((
        TileId::new(5, 10, 11, (T0 + BUCKET).max(0) as u64),
        T0 + BUCKET,
        T0 + 2 * BUCKET - 1,
        0,
        empty_layer(),
    ));
    out
}

/// Build one golden dataset (single or paged directory) into `out`.
///
/// Everything is deterministic: fixed payload content, `SpatialMajor` ordering
/// (independent of the Auto heuristic), fixed pack target, default zstd level.
///
/// TWO PASSES, in the order the builder runs them:
///   1. [`corpus_layers`] → [`golden_pins`] — the dataset-global verdicts.
///   2. `encode_tile_with` against a config carrying those pins.
///
/// The writer is created FIRST because a layer frame references its schema
/// template by hash: the encoder needs the writer's collector before
/// the first `encode_tile_with` or the template never lands in `manifest.schemas`
/// and the archive decodes to nothing.
fn build_v2_dataset(out: &Path, paging: Option<usize>) -> stt_core::Manifest {
    let bucket = BUCKET;
    let t0 = T0;

    let mut writer = PackWriter::create(out, BlobOrdering::SpatialMajor, 4 * 1024)
        .unwrap()
        .with_paging(paging)
        .with_capabilities(vec![
            CAPABILITY_COORD_QUANT.to_string(),
            CAPABILITY_ATTR_QUANT.to_string(),
            // The encoder config below leaves `compact_times` at its default
            // (on), so these frames carry `TILE_META.st`/`et` — a shape a
            // reader must understand to reconstruct absolute times. Declaring
            // it keeps the fixture a CONFORMANT archive, matching what
            // `stt-build`'s `required_capabilities()` emits; a fixture that
            // used the shape without declaring it would pin a spec violation.
            CAPABILITY_TIME_DELTA.to_string(),
        ]);
    // The pin is on the DEFAULT emission — formatVersion 3 is not requested
    // here, it is what
    // an unconfigured writer produces. If the default ever moves, this fires
    // with a readable message instead of a wall of byte diffs.
    assert_eq!(stt_core::pack::PACKED_FORMAT_VERSION, 3);
    assert_eq!(stt_core::arrow_tile::LAYER_FRAME_VERSION, 2);

    let corpus = corpus_layers();
    // --- Pass 1 ---------------------------------------------------------
    let pins = Arc::new(golden_pins(corpus.iter().map(|(_, _, _, _, l)| l)));
    // A pin set that decided nothing would put the whole corpus back on the
    // incumbent per-tile path and leave this fixture blind to mechanism M2 —
    // the defect this shape exists to close. Assert the two verdicts that make
    // the corpus load-bearing, here rather than only in a test, so a
    // regeneration cannot mint a blind fixture even if run in isolation.
    assert!(
        matches!(
            pins.dict.get("kind"),
            Some(GlobalDictVerdict::Dictionary(_))
        ),
        "the corpus must be large enough that the dataset-global dictionary \
         verdict for `kind` is Dictionary — it is Utf8, so this fixture would \
         pin nothing new (see KINDS)"
    );
    assert_eq!(
        pins.attr.get("count").map(|p| p.leaf),
        Some(PinnedLeaf::I32),
        "the corpus must keep `count`'s dataset span above the UInt16 index \
         space, or the leaf-width pin is a no-op"
    );
    // --- Pass 2 ---------------------------------------------------------
    let cfg = golden_encoder_config(&writer, &pins);

    // (id, time_start, time_end, feature_count, payload)
    let tiles: Vec<(TileId, i64, i64, u32, Vec<u8>)> = corpus
        .iter()
        .map(|(id, ts, te, n, layer)| {
            let payload = encode_tile_with(std::slice::from_ref(layer), &cfg).unwrap();
            (*id, *ts, *te, *n, payload)
        })
        .collect();

    for (id, ts, te, n, payload) in &tiles {
        writer
            .add_tile_full(id, *ts, *te, Some(*ts), *n, Some(bucket as u64), payload)
            .unwrap();
    }
    let meta = Metadata::new("v2-golden")
        .with_description("Default formatVersion-3 byte-identity fixture")
        .with_zoom_levels(5, 5)
        .with_temporal_bucket_ms(bucket as u64)
        .with_time_range(stt_core::types::TimeRange::new(
            t0 as u64,
            (t0 + 2 * bucket - 1) as u64,
        ));
    writer.finalize(&meta).unwrap()
}

/// Recursively collect `relative path → file bytes` for a dataset directory.
fn collect_files(root: &Path) -> BTreeMap<String, Vec<u8>> {
    fn walk(root: &Path, dir: &Path, out: &mut BTreeMap<String, Vec<u8>>) {
        for entry in fs::read_dir(dir).unwrap() {
            let path = entry.unwrap().path();
            if path.is_dir() {
                walk(root, &path, out);
            } else {
                let rel = path
                    .strip_prefix(root)
                    .unwrap()
                    .components()
                    .map(|c| c.as_os_str().to_string_lossy())
                    .collect::<Vec<_>>()
                    .join("/");
                out.insert(rel, fs::read(&path).unwrap());
            }
        }
    }
    let mut out = BTreeMap::new();
    walk(root, root, &mut out);
    out
}

/// Both dataset shapes, keyed by fixture subdirectory.
fn dataset_shapes() -> [(&'static str, Option<usize>); 2] {
    [("single", None), ("paged", Some(3))]
}

/// The formatVersion-3 writer reproduces the committed golden corpus
/// byte-for-byte: every
/// object file AND the manifest, plus the recorded blake3 of each object.
///
/// ⚠ **EXPECTED RED between the M2 pin landing and TB-14.** The committed
/// corpus was generated on the incumbent per-tile path (`global_pins: None`);
/// this builder now runs the two-pass pinned path, so every object it touches
/// re-addresses. That is the point — the pin can now SEE mechanism M2, which is
/// the whole reason it was rewired. The corpus is deliberately NOT regenerated
/// here: golden pins move exactly once in this program, under the plan's TB-14
/// (rebuild window R1), after the M2 mechanism is complete and
/// semantic-fingerprint characterized. Re-blessing it now would have to be
/// undone the moment the remaining M2 wiring lands, and re-blessing twice is
/// how a pin stops meaning anything. If you are reading this because your build
/// went red: this is not your bug, and the fix is not to regenerate.
#[test]
fn v2_build_is_byte_identical_to_golden() {
    let fixture_root = fixture_dir();
    assert!(
        fixture_root.exists(),
        "missing fixture {} — the committed golden corpus pins the current \
         writer's DEFAULT (formatVersion-3) emission; regenerate ONLY alongside \
         an intentional, reviewed format change (see the header comment)",
        fixture_root.display()
    );
    let expected_hashes: BTreeMap<String, String> =
        serde_json::from_slice(&fs::read(fixture_root.join("expected-hashes.json")).unwrap())
            .unwrap();

    let tmp = tempfile::tempdir().unwrap();
    let mut rebuilt_hashes: BTreeMap<String, String> = BTreeMap::new();
    for (name, paging) in dataset_shapes() {
        let out = tmp.path().join(name);
        let manifest = build_v2_dataset(&out, paging);
        // A formatVersion-3 manifest with no templates would mean the frames
        // fell back to inline schemas — the fixture would then pin un-hoisted
        // output under a formatVersion-3 label and never notice a hoist
        // regression.
        assert!(
            !manifest.schemas.is_empty(),
            "[{name}] formatVersion-3 manifest must carry schema templates"
        );

        let golden = collect_files(&fixture_root.join(name));
        let rebuilt = collect_files(&out);
        assert_eq!(
            golden.keys().collect::<Vec<_>>(),
            rebuilt.keys().collect::<Vec<_>>(),
            "[{name}] object set drifted from the golden fixture — EXPECTED \
             while the M2 two-pass build is landing (the committed corpus \
             predates `EncoderConfig::global_pins`; it is regenerated ONCE, \
             under TB-14 / rebuild window R1, never here). Otherwise this is \
             the content-address churn the pin exists to catch"
        );
        for (rel, bytes) in &rebuilt {
            assert_eq!(
                golden.get(rel).unwrap(),
                bytes,
                "[{name}] {rel}: bytes differ from the golden fixture — the \
                 DEFAULT emission re-addressed every object it touches (new pack \
                 names, cold edge caches, a full re-upload). EXPECTED while the \
                 M2 two-pass build is landing: the committed corpus predates \
                 `EncoderConfig::global_pins` and is regenerated ONCE, under \
                 TB-14 / rebuild window R1, not here. Otherwise: if the change \
                 is intentional, regenerate the fixture in the SAME commit; if \
                 not, this is the encoder drift the pin exists to catch"
            );
            rebuilt_hashes.insert(format!("{name}/{rel}"), blake3_128_hex(bytes));
        }
    }
    assert_eq!(
        expected_hashes, rebuilt_hashes,
        "recorded blake3 pins drifted from the rebuilt datasets"
    );
}

/// The fixture is a real archive, not just bytes: it opens through the packed
/// reader and every tile decodes via the manifest's template registry. Without
/// this, a regenerated-but-broken fixture would still "pass" the byte pin
/// (it would be pinning garbage).
///
/// It also pins the one thing the byte comparison structurally cannot: that the
/// wire's COMPACT time shape (`TILE_META.st`/`et` — u32 offsets from `t0` and
/// u32 durations, or an omitted `end_time` entirely) is fully re-inflated on
/// the way out. Every decoded layer must present the same non-null absolute
/// `Int64` start/end pair a reader has always seen, with the exact millisecond
/// values the encoder was handed. If the re-inflate regresses, the archive
/// still decodes — it just silently reports times near zero — so only an
/// explicit value assertion catches it.
#[test]
fn v2_golden_fixture_decodes_through_the_reader() {
    use arrow::array::{Array, Int64Array};
    use arrow::datatypes::DataType;

    let fixture_root = fixture_dir();
    for (name, _) in dataset_shapes() {
        let manifest_path = fixture_root.join(name).join("manifest.json");
        let reader = stt_core::PackedReader::open(&manifest_path)
            .unwrap_or_else(|e| panic!("[{name}] open golden fixture: {e}"));
        assert_eq!(
            reader.format_version(),
            stt_core::pack::PACKED_FORMAT_VERSION,
            "[{name}] fixture must declare formatVersion 3"
        );
        let registry = reader
            .templates()
            .unwrap_or_else(|| panic!("[{name}] formatVersion-3 fixture must expose a registry"));
        let mut rows = 0usize;
        let mut min_start = i64::MAX;
        for entry in reader.entries() {
            let payload = reader
                .read_payload(entry)
                .unwrap_or_else(|e| panic!("[{name}] {:?} payload: {e}", entry.tile_id()));
            let layers = stt_core::arrow_tile::decode_tile_with_templates(&payload, registry)
                .unwrap_or_else(|e| panic!("[{name}] {:?} decode: {e}", entry.tile_id()));
            rows += layers.iter().map(|l| l.batch.num_rows()).sum::<usize>();

            for layer in &layers {
                for col in ["start_time", "end_time"] {
                    let field = layer
                        .batch
                        .schema()
                        .field_with_name(col)
                        .unwrap_or_else(|_| panic!("[{name}] layer '{}' has no {col}", layer.name))
                        .clone();
                    assert_eq!(
                        field.data_type(),
                        &DataType::Int64,
                        "[{name}] layer '{}': {col} must decode as absolute Int64, \
                         not the compact wire width",
                        layer.name
                    );
                    let arr = layer.batch.column_by_name(col).unwrap();
                    assert_eq!(
                        arr.null_count(),
                        0,
                        "[{name}] layer '{}': {col} must be non-null",
                        layer.name
                    );
                    let times = arr.as_any().downcast_ref::<Int64Array>().unwrap();
                    for i in 0..times.len() {
                        let v = times.value(i);
                        if col == "start_time" {
                            min_start = min_start.min(v);
                        }
                        // A failed re-inflate leaves raw offsets (0-ish) or raw
                        // durations here; every real feature in this corpus is
                        // anchored at/after the 2023-11-14 base.
                        assert!(
                            v >= 1_700_000_000_000,
                            "[{name}] layer '{}': {col}[{i}] = {v} is not an absolute \
                             Unix-ms timestamp — the compact-time re-inflate regressed",
                            layer.name
                        );
                    }
                }
            }
        }
        // 4 point tiles × 5 + 1 trajectory tile × 2 + 1 empty tile × 0.
        assert_eq!(rows, 22, "[{name}] decoded feature total");
        // `point_layer(0, ..)` starts exactly at the corpus base.
        assert_eq!(
            min_start, 1_700_000_000_000,
            "[{name}] earliest decoded start_time"
        );
    }
}

/// The corpus can SEE mechanism M2 — the property this file exists to hold, and
/// the one a byte pin structurally cannot check about itself.
///
/// A golden fixture built at `..EncoderConfig::default()` leaves
/// `global_pins: None`, encodes on the incumbent per-tile path, and stays green
/// through every byte the pinned path moves. It looks like a pin, it diffs like
/// a pin, and it guards nothing — the same shape as a guard iterating an empty
/// collection, or a fingerprint suite whose single tile happened to hold every
/// feature. This test asserts the corpus is not that, and it does so WITHOUT
/// reading a committed byte, so it holds continuously — before TB-14's
/// regeneration, during it, and after.
///
/// Five claims, each about a different way the pin could go blind:
///   1. every property column the corpus carries actually resolves a pin;
///   2. `kind` resolves a DICTIONARY (not the `Utf8` degrade) against the whole
///      dataset list in first-seen order;
///   3. every tile holds a STRICT SUBSET of that list, so "ship the full list
///      in every tile" is a claim the bytes can disagree with;
///   4. no tile's own numeric verdict equals the dataset's — the affines and
///      the `count` leaf width genuinely move;
///   5. and the bytes prove it: every tile encodes differently with the pins
///      than without them.
#[test]
fn golden_fixture_exercises_the_pinned_path() {
    let corpus = corpus_layers();
    let pins = golden_pins(corpus.iter().map(|(_, _, _, _, l)| l));

    // (1) Nothing unpinned. A column absent from the pins silently keeps the
    // per-tile path, which is the fallback — correct in production, blind in a
    // fixture whose whole job is to exercise the pinned one.
    assert_eq!(
        pins.attr.keys().map(String::as_str).collect::<Vec<_>>(),
        ["count", "speed"],
        "every numeric column of the corpus must resolve a pin"
    );
    assert_eq!(
        pins.dict.keys().map(String::as_str).collect::<Vec<_>>(),
        ["kind"],
        "every categorical column of the corpus must resolve a pin"
    );

    // (2) The dictionary verdict, against the dataset-global list. `Utf8` here
    // would be a legal pin that happens to encode exactly what the per-tile
    // rule already picks for tiles this small — i.e. a no-op.
    let Some(GlobalDictVerdict::Dictionary(categories)) = pins.dict.get("kind") else {
        panic!(
            "`kind` must pin a Dictionary, not Utf8 — the corpus has shrunk \
             below the dataset-scale crossover (see KINDS)"
        );
    };
    assert_eq!(
        categories.iter().map(String::as_str).collect::<Vec<_>>(),
        KINDS.to_vec(),
        "the pinned list must be the whole dataset domain in FIRST-SEEN order"
    );

    // (3) Strict subsets everywhere: no tile carries the full list, so a
    // tile-local dictionary is distinguishable from the hoisted one in the
    // bytes. The empty tile is the extreme case (zero of four) and the point
    // tiles the ordinary one (two of four).
    let mut proper_nonempty_subsets = 0usize;
    for (id, _, _, _, layer) in &corpus {
        let Some((_, PropertyColumn::Categorical(values))) =
            layer.properties.iter().find(|(n, _)| n == "kind")
        else {
            continue;
        };
        let mut distinct: Vec<&str> = Vec::new();
        for v in values.iter().flatten() {
            if !distinct.contains(&v.as_str()) {
                distinct.push(v.as_str());
            }
        }
        assert!(
            distinct.len() < categories.len(),
            "{id:?} holds all {} categories — no tile may carry the full \
             dataset list, or the hoist's all-or-nothing contract is untested",
            categories.len()
        );
        if !distinct.is_empty() {
            proper_nonempty_subsets += 1;
        }
    }
    assert!(
        proper_nonempty_subsets >= 4,
        "the corpus needs several tiles holding a non-empty PROPER subset; \
         got {proper_nonempty_subsets}"
    );

    // (4) The numeric verdicts move. `golden_pins` over ONE layer is exactly
    // the per-tile rule (`derive_auto` over that tile's own statistics), so
    // comparing it to the dataset pin is a like-for-like read of "which
    // evidence did the rule see".
    let speed_pin = *pins.attr.get("speed").unwrap();
    let count_pin = *pins.attr.get("count").unwrap();
    assert_eq!(
        count_pin.leaf,
        PinnedLeaf::I32,
        "`count`'s dataset span must exceed the UInt16 index space"
    );
    let (mut speed_columns, mut speed_moved) = (0usize, 0usize);
    let (mut count_columns, mut count_narrower) = (0usize, 0usize);
    for (id, _, _, _, layer) in &corpus {
        let local = golden_pins(std::iter::once(layer));
        if let Some(local_speed) = local.attr.get("speed") {
            speed_columns += 1;
            assert_ne!(
                *local_speed, speed_pin,
                "{id:?}: this tile's own `speed` affine equals the dataset pin, \
                 so pinning changes nothing here"
            );
            speed_moved += 1;
        }
        if let Some(local_count) = local.attr.get("count") {
            count_columns += 1;
            if local_count.leaf == PinnedLeaf::U16 {
                count_narrower += 1;
            }
        }
    }
    assert_eq!(
        (speed_columns, speed_moved),
        (6, 6),
        "every layer carrying `speed` must disagree with the dataset pin"
    );
    assert_eq!(
        (count_columns, count_narrower),
        (5, 5),
        "every tile carrying `count` must fit UInt16 on its own, so the pinned \
         Int32 leaf is the dataset's verdict and nobody else's"
    );

    // (5) The bytes. Two encodes of each tile under configs that differ ONLY in
    // `global_pins` — the direct refutation of "the fixture would look the same
    // either way". `template_collector` is None on both: this is an A/B of the
    // pins, and self-contained frames keep it free of writer state.
    let unpinned = EncoderConfig {
        quantize_coords_m: Some(1.0),
        quantize_attrs_auto: true,
        format_version: stt_core::arrow_tile::LAYER_FRAME_VERSION,
        ..EncoderConfig::default()
    };
    let pinned = EncoderConfig {
        global_pins: Some(Arc::new(pins.clone())),
        ..unpinned.clone()
    };
    for (id, _, _, _, layer) in &corpus {
        let layers = std::slice::from_ref(layer);
        let a = encode_tile_with(layers, &unpinned).unwrap();
        let b = encode_tile_with(layers, &pinned).unwrap();
        assert_ne!(
            a, b,
            "{id:?} encodes IDENTICALLY with and without the dataset-global \
             pins — this tile is invisible to mechanism M2, and pinning its \
             bytes would guard nothing"
        );
        // Visible under `--nocapture`, for whoever runs TB-14: how far the pins
        // move each tile is the size of the mechanism this corpus can see. The
        // CONTENT always differs (asserted above); the length need not — the
        // trajectory tile carries only `speed`, whose pin moves the `stt:qa`
        // VALUES without changing the column's shape.
        println!(
            "{id:?}: unpinned {} B → pinned {} B (len {:+}, content differs)",
            a.len(),
            b.len(),
            b.len() as i64 - a.len() as i64
        );
    }
}

/// Fixture generator — regenerating REPLACES the byte pin, so run it ONLY
/// alongside an intentional, reviewed change to formatVersion-3 emission
/// (see header).
#[test]
#[ignore = "fixture regeneration replaces the formatVersion-3 byte-stability pin"]
fn regenerate_v2_golden() {
    let fixture_root = fixture_dir();
    if fixture_root.exists() {
        fs::remove_dir_all(&fixture_root).unwrap();
    }
    fs::create_dir_all(&fixture_root).unwrap();

    let mut hashes: BTreeMap<String, String> = BTreeMap::new();
    for (name, paging) in dataset_shapes() {
        let out = fixture_root.join(name);
        build_v2_dataset(&out, paging);
        for (rel, bytes) in collect_files(&out) {
            hashes.insert(format!("{name}/{rel}"), blake3_128_hex(&bytes));
        }
    }
    fs::write(
        fixture_root.join("expected-hashes.json"),
        serde_json::to_vec_pretty(&hashes).unwrap(),
    )
    .unwrap();
    println!("wrote the golden corpus to {}", fixture_root.display());
}
